fix engine runtime errors due to package private access (#111)
* engine: override and copy loadHistoryUUID implemention from OS-core engine

```

[2025-10-23T21:30:59,534][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [integTest-0] fatal error in thread [opensearch[integTest-0][generic][T#3]], exiting
java.lang.IllegalAccessError: class org.opensearch.index.engine.TSDBEngine tried to access method 'java.lang.String org.opensearch.index.engine.Engine.loadHistoryUUID(java.util.Map)' (org.opensearch.index.engine.TSDBEngine is in unnamed module of loader java.net.FactoryURLClassLoader @38d525aa; org.opensearch.index.engine.Engine is in unnamed module of loader 'app')
        at org.opensearch.index.engine.TSDBEngine.<init>(TSDBEngine.java:147) ~[?:?]
        at org.opensearch.index.engine.TSDBEngine.<init>(TSDBEngine.java:99) ~[?:?]
        at org.opensearch.index.engine.TSDBEngineFactory.newReadWriteEngine(TSDBEngineFactory.java:31) ~[?:?]
        at org.opensearch.index.shard.IndexShard.innerOpenEngineAndTranslog(IndexShard.java:2885) ~[opensearch-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at org.opensearch.index.shard.IndexShard.openEngineAndRecoverFromTranslog(IndexShard.java:2787) ~[opensearch-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at org.opensearch.index.shard.IndexShard.openEngineAndRecoverFromTranslog(IndexShard.java:2757) ~[opensearch-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at org.opensearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:763) ~[opensearch-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at org.opensearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:129) ~[opensearch-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at org.opensearch.core.action.ActionListener.completeWith(ActionListener.java:344) ~[opensearch-core-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at org.opensearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:124) ~[opensearch-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at org.opensearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:3175) ~[opensearch-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:89) ~[opensearch-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:975) ~[opensearch-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

Signed-off-by: phiiip <22754958+philiplhchan@users.noreply.github.com>

* fix isFromTranslog access error

```

»  fatal error in thread [opensearch[integTest-0][write][T#1]], exiting
»  java.lang.IllegalAccessError: class org.opensearch.index.engine.TSDBEngine tried to access method 'boolean org.opensearch.index.engine.Engine$Operation$Origin.isFromTranslog()' (org.opensearch.index.engine.TSDBEngine is in unnamed module of loader java.net.FactoryURLClassLoader @2a7bc16b; org.opensearch.index.engine.Engine$Operation$Origin is in unnamed module of loader 'app')
»       at org.opensearch.index.engine.TSDBEngine.rewriteParsedDocumentSource(TSDBEngine.java:946)
»       at org.opensearch.index.engine.TSDBEngine.index(TSDBEngine.java:238)
»       at org.opensearch.index.shard.IndexShard.index(IndexShard.java:1292)
»       at org.opensearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:1231)
»       at org.opensearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:1122)
»       at org.opensearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:646)
»       at org.opensearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:472)
»       at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
»       at org.opensearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:556)
»       at org.opensearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:417)
»       at org.opensearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:126)
»       at org.opensearch.action.support.replication.TransportWriteAction$1.doRun(TransportWriteAction.java:275)
»       at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:975)
»       at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
»       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
»       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
»       at java.base/java.lang.Thread.run(Thread.java:1583)
```

```

»   ↓ last 40 non error or warning messages from /home/user/opensearch/philiplhchan-opensearch-tsdb-internal/build/testclusters/integTest-0/logs/opensearch.stderr.log ↓
» WARNING: Using incubator modules: jdk.incubator.vector
»  WARNING: Unknown module: org.apache.arrow.memory.core specified to --add-opens
»  fatal error in thread [opensearch[integTest-0][write][T#1]], exiting
»  java.lang.IllegalAccessError: class org.opensearch.index.engine.TSDBEngine tried to access method 'boolean org.opensearch.index.engine.Engine$Operation$Origin.isFromTranslog()' (org.opensearch.index.engine.TSDBEngine is in unnamed module of loader java.net.FactoryURLClassLoader @2a7bc16b; org.opensearch.index.engine.Engine$Operation$Origin is in unnamed module of loader 'app')
»       at org.opensearch.index.engine.TSDBEngine.rewriteParsedDocumentSource(TSDBEngine.java:946)
»       at org.opensearch.index.engine.TSDBEngine.index(TSDBEngine.java:238)
»       at org.opensearch.index.shard.IndexShard.index(IndexShard.java:1292)
»       at org.opensearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:1231)
»       at org.opensearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:1122)
»       at org.opensearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:646)
»       at org.opensearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:472)
»       at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
»       at org.opensearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:556)
»       at org.opensearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:417)
»       at org.opensearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:126)
»       at org.opensearch.action.support.replication.TransportWriteAction$1.doRun(TransportWriteAction.java:275)
»       at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:975)
»       at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
»       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
»       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
»       at java.base/java.lang.Thread.run(Thread.java:1583)
```

Signed-off-by: phiiip <22754958+philiplhchan@users.noreply.github.com>

---------

Signed-off-by: phiiip <22754958+philiplhchan@users.noreply.github.com>